### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by cpfreitas** [mnansary/pyWLFRFD#7]
Hi, I'm very interested in this model, can you shared your dataset?

**Comment by mnansary** [comment]
Hello, thank you for your interest. Unfortunately, the dataset is not public and I will need to contact my collaborators for their permission to share it (it is bought from an organization in bangladesh). If I can manage the dataset i can provide it for free, however, getting the permission will need some time.

**Comment by cpfreitas** [comment]
If you can provide to me a sample that to know how I need to format my data, than I can test with my dataset.
Thanks!

**Comment by mnansary** [comment]
@cpfreitas sorry for the late reply . I have actually lost access to the data unfortunately :(  (this project was done a really long time ago). The person who owns the data is : https://github.com/jamal919 . You can contact him personally. 
About the data structre: the data was in a csv file: 
datetime, lat_lon_point_1, lat_lon_point_2 ,lat_lon_point_3 , ....target_water_level_at_x
the columns held the following data
datetime -> timedata
lat_lon_point_  ->rain_fall_height(mm) 
arget_water_level_at_x -> water_level_height_in_m 

for every location (in this case, a specific latitude and longitude ) rainfall heights were collected and a specific outlet was selected for predicting the water level data. For the modeling 
Feature=X-> 7 days data [water level data at target and rainfall data at all relevant points] normalized with respect to corresponding metric calc(i.e rainfall normalized with respect to millimeter-scale data and waterlevel with respect to meter-scale data  
Target/output-> WaterLevel at target point on the 8th daya
Hope this helps
